### ISSUE TITLE
Icons for Release 1.4.1

### ISSUE THREAD

**Issue by leifniem** [Delta-Icons/android#96]
# Todo for Version 1.4.1

Opening the Requests brought in a flood of new icons to create, these are those already included that need fixing, as well as those that were beyond the most requested and did not belong to games that permanently change their icons.

## TO UPDATE

- [x] Banking
de.commerzbanking.mobil/com.neugelb.banking.features.startup.SplashActivity

- [x] Spark
com.readdle.spark/com.readdle.spark.ui.MainActivity

- [x] Notes
com.samsung.android.app.notes/com.samsung.android.app.notes.memolist.MemoListActivity

- [x] Ecosia
com.ecosia.android/com.google.android.apps.chrome.Main

- [x] DuckDuckGo
com.duckduckgo.mobile.android/com.duckduckgo.app.launch.Launcher

- [x] Music
code.name.monkey.retromusic/code.name.monkey.retromusic.activities.MainActivity

- [x] Device
com.google.android.apps.adm/com.google.android.apps.adm.activities.MainActivity

- [x] ING
www.ingdirect.nativeframe/es.ingdirect.www.LandingActivity

- [x] Blokada
org.blokada.origin.alarm/core.PanelActivity

- [x] Keepass2Android
keepass2android.keepass2android/md5b85ab5ea2545156b0f09600c184a5178.KeePass

- [x] Duty
com.garena.game.codm/com.tencent.tmgp.cod.PermissionGrantActivity

- [x] Preview
org.mozilla.fenix/org.mozilla.fenix.App

- [x] SoloLearn
com.sololearn/com.sololearn.app.ui.launcher.LauncherActivity

- [x] Music
com.bsbportal.music/com.bsbportal.music.v2.features.main.ui.HomeActivity

- [x] Alarmas
com.lge.clock/com.lge.clock.DefaultAlarmClockActivity

- [x] Bank
com.usbank.mobilebanking/com.usb.module.environment.ui.SplashActivity

- [x] Houseparty
com.herzick.houseparty/com.lifeonair.houseparty.ui.routing.RoutingActivity

- [x] 9GAG
com.ninegag.android.app/com.ninegag.android.app.ui.home.HomeActivity

- [x] WhatsApp
com.gbwhatsapp/com.gbwhatsapp.8

- [x] ADM
com.dv.adm/com.dv.get.Main

- [x] Cleanup
com.avast.android.cleaner/com.avast.android.cleaner.activity.StartActivity

- [x] Club
com.nike.plusgps/com.nike.plusgps.SplashActivity

- [x] Sparkasse
com.starfinanz.smob.android.sfinanzstatus/com.starfinanz.smob.android.sfinanzstatus.launcher_d2e0d35b0d2e12e29c6ccf966a5435faae9646169ae568656ab4a71cdfe6399d

- [x] Music
com.sec.android.app.music/com.samsung.musicplus.MusicMainPagerActivity

- [x] GIPHY
com.giphy.messenger/com.giphy.messenger.app.OnboardingActivity

- [x] Freecharge
com.freecharge.android/com.freecharge.activities.splash.SplashActivity

- [x] Connect
net.openvpn.openvpn/net.openvpn.unified.MainActivity

- [x] Yousician
com.yousician.yousician/com.yousician.yousiciannative.YousicianActivity

- [x] Vodafone
com.myvodafoneapp/com.tsse.vfuk.view.VFLaunchActivity

- [x] Music
com.oppo.music/com.oppo.music.MainListActivity

- [x] TunnelBear
com.tunnelbear.android/com.tunnelbear.android.main.SplashActivity

- [x] Guardian
com.guardian/com.guardian.feature.stream.NewHomeActivity

- [x] Pay
com.google.android.apps.nbu.paisa.user/com.google.android.apps.nbu.paisa.user.launcher.LauncherActivity

- [x] 2
com.lightricks.facetune.free/com.lightricks.facetune.SplashActivity

- [x] Classroom
com.google.android.apps.classroom/com.google.android.apps.classroom.application.launcher.LauncherActivity

- [x] Musixmatch
com.musixmatch.android.lyrify/com.musixmatch.android.presentation.activities.SplashActivity

- [x] Textra
com.textra/com.mplus.lib.Main_fff57f17

- [x] (AOSP)
com.android.inputmethod.latin/com.android.inputmethod.latin.setup.SetupActivity

- [x] Gaana
com.gaana/com.gaana.SplashScreenActivity

- [x] Deemo
com.rayark.pluto/com.google.firebase.MessagingUnityPlayerActivity

- [x] Calendar
org.lineageos.etar/com.android.calendar.AllInOneActivity

- [x] SBB
ch.sbb.mobile.android.b2c/ch.sbb.mobile.android.vnext.splashscreen.SplashScreenActivity

- [x] Microsoft Launcher
com.microsoft.launcher.zan/com.microsoft.launcher.Launcher

- [x] Calculator
com.coloros.calculator/com.android.calculator2.Calculator

- [x] Clock
com.android.BBKClock/com.android.BBKClock.Timer

- [x] Nike
com.nike.ntc/com.nike.ntc.onboarding.OnboardingSplashActivity

- [x] HBO Go
com.hbo.broadband/com.hbo.broadband.startup.SplashActivity

- [x] Amex Mobile
com.americanexpress.android.acctsvcs.uk/com.americanexpress.android.intl.app.view.activity.SplashActivity

- [x] qr code reader
app.qrcode/app.qrcode.MainActivity

- [x] Gallery
com.coloros.gallery3d/com.oppo.gallery3d.app.Gallery

- [x] ConvertPad
com.cvpad.mobile.android.wt.unit/com.cvpad.mobile.android.wt.unit.UnitActivity

- [x] Vodafone
com.emeint.android.myservices/vodafone.vis.engezly.ui.screens.splash.SplashRevampActivity

- [x] Weather
com.coloros.weather/com.coloros.weather.OppoMainActivity

- [x] Contacts
com.samsung.android.app.contacts/com.samsung.android.contacts.contactslist.PeopleActivity

- [x] Lawnchair Launcher
ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.LawnchairLauncher

- [x] Komoot
de.komoot.android/de.komoot.android.ui.inspiration.InspirationActivity

- [x] File Manager
zte.com.cn.filer/zte.com.cn.filer.FileMgrActivity

## TO CREATE

- [x] Franco Kernel Manager
com.franco.kernel/a.spl
https://play.google.com/store/apps/details?id=com.franco.kernel

- [x] Earth
com.mojang.minecraftearth/com.mojang.minecraftpe.MainActivity
https://play.google.com/store/apps/details?id=com.mojang.minecraftearth

- [x] Paint
com.medibang.android.paint.tablet/com.medibang.android.paint.tablet.ui.activity.LauncherActivity
https://play.google.com/store/apps/details?id=com.medibang.android.paint.tablet

- [x] Gojek
com.gojek.app/com.gojek.home.GojekSplash
https://play.google.com/store/apps/details?id=com.gojek.app

- [x] Space
com.oneplus.gamespace/com.oneplus.gamespace.ui.main.MainActivity
https://play.google.com/store/apps/details?id=com.oneplus.gamespace

- [x] Roblox
com.roblox.client/com.roblox.client.startup.ActivitySplash
https://play.google.com/store/apps/details?id=com.roblox.client

- [x] Swiggy
in.swiggy.android/in.swiggy.android.activities.HomeActivity
https://play.google.com/store/apps/details?id=in.swiggy.android

- [x] Gaming
com.facebook.games/com.facebook.games.app.login.GamesLoginActivity
https://play.google.com/store/apps/details?id=com.facebook.games

- [x] XRecorder
videoeditor.videorecorder.screenrecorder/com.inshot.screenrecorder.activities.SplashBeforeActivity
https://play.google.com/store/apps/details?id=videoeditor.videorecorder.screenrecorder

- [x] BeautyPlus
com.commsource.beautyplus/com.commsource.beautyplus.start.StartUpAdvertActivity
https://play.google.com/store/apps/details?id=com.commsource.beautyplus

- [x] Prayer
com.haz.prayer/com.haz.prayer.MyPrayer
https://play.google.com/store/apps/details?id=com.haz.prayer

- [x] Careem
com.careem.acma/com.careem.superapp.core.onboarding.activity.OnboardingActivity
https://play.google.com/store/apps/details?id=com.careem.acma

- [x] Stars
com.supercell.brawlstars/com.supercell.brawlstars.GameApp
https://play.google.com/store/apps/details?id=com.supercell.brawlstars

- [x] PPSSPP
org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity
https://play.google.com/store/apps/details?id=org.ppsspp.ppsspp

- [x] NAVER
com.nhn.android.search/com.nhn.android.search.ui.pages.SearchHomePage
https://play.google.com/store/apps/details?id=com.nhn.android.search

- [x] Connect
com.garmin.android.apps.connectmobile/com.garmin.android.apps.connectmobile.GCMActivityStartup
https://play.google.com/store/apps/details?id=com.garmin.android.apps.connectmobile

- [x] Google Go
com.google.android.apps.searchlite/com.google.android.apps.searchlite.ui.SearchActivity
https://play.google.com/store/apps/details?id=com.google.android.apps.searchlite

- [x] PhonePe
com.phonepe.app/com.phonepe.app.v4.nativeapps.splash.Navigator_SplashActivity
https://play.google.com/store/apps/details?id=com.phonepe.app

- [x] GitHub
com.github.android/com.github.android.activities.MainActivity
https://play.google.com/store/apps/details?id=com.github.android

- [x] SmartThings
com.samsung.android.oneconnect/com.samsung.android.oneconnect.ui.SCMainActivity
https://play.google.com/store/apps/details?id=com.samsung.android.oneconnect

- [x] Deliveroo
com.deliveroo.orderapp/com.deliveroo.orderapp.appicon.default
https://play.google.com/store/apps/details?id=com.deliveroo.orderapp

- [x] Recorder
com.google.android.apps.recorder/com.google.android.apps.recorder.ui.recordings.MainActivity
https://play.google.com/store/apps/details?id=com.google.android.apps.recorder

- [x] PES 2020
jp.konami.pesam/com.epicgames.ue4.SplashActivity
https://play.google.com/store/apps/details?id=jp.konami.pesam

- [x] Samsung usb Backup
com.sec.android.autobackup/com.sec.android.autobackup.AutoBackupLauncherActivity
https://play.google.com/store/apps/details?id=com.sec.android.autobackup

- [x] Lens
com.google.ar.lens/com.google.vr.apps.ornament.app.lens.LensLauncherActivity
https://play.google.com/store/apps/details?id=com.google.ar.lens

- [x] InShot
com.camerasideas.instashot/com.camerasideas.instashot.DummyActivity
https://play.google.com/store/apps/details?id=com.camerasideas.instashot

- [x] Amazon Seller
com.amazon.sellermobile.android/com.amazon.mShop.home.MainActivity
https://play.google.com/store/apps/details?id=com.amazon.sellermobile.android

- [x] YMusic
com.kapp.youtube.final/com.kapp.youtube.ui.MainActivity
https://play.google.com/store/apps/details?id=com.kapp.youtube.final

- [x] Blackboard
com.blackboard.android.bbstudent/com.blackboard.android.bbstudent.launch.LaunchActivityImpl
https://play.google.com/store/apps/details?id=com.blackboard.android.bbstudent

- [x] Airtel
com.myairtelapp/com.myairtelapp.activity.SplashScreenActivity
https://play.google.com/store/apps/details?id=com.myairtelapp

- [x] Clue
com.clue.android/com.biowink.clue.splash.SplashActivity
https://play.google.com/store/apps/details?id=com.clue.android

- [x] TaoBao
com.taobao.taobao/com.taobao.tao.welcome.Welcome
https://play.google.com/store/apps/details?id=com.taobao.taobao

- [x] Notes
com.oneplus.note/com.oneplus.note.ui.MainActivity
https://play.google.com/store/apps/details?id=com.oneplus.note

- [x] Themes
com.samsung.android.themestore/com.samsung.android.themestore.activity.Launcher
https://play.google.com/store/apps/details?id=com.samsung.android.themestore

- [x] Tips
com.samsung.android.app.tips/com.samsung.android.app.tips.TipsMainActivity
https://play.google.com/store/apps/details?id=com.samsung.android.app.tips

- [x] Pratilipi
com.pratilipi.mobile.android/com.pratilipi.mobile.android.deepLinking.DeepLinkingActivity
https://play.google.com/store/apps/details?id=com.pratilipi.mobile.android

- [x] samsung care
com.samsung.android.lool/com.samsung.android.sm.ui.DefaultActivity
https://play.google.com/store/apps/details?id=com.samsung.android.lool

- [x] Cake
me.mycake/me.mycake.MainActivity
https://play.google.com/store/apps/details?id=me.mycake

- [x] CoronaWarn
de.rki.coronawarnapp/de.rki.coronawarnapp.ui.LauncherActivity
https://play.google.com/store/apps/details?id=de.rki.coronawarnapp

- [x] PayPay
jp.ne.paypay.android.app/jp.ne.paypay.android.app.MainActivity
https://play.google.com/store/apps/details?id=jp.ne.paypay.android.app

- [x] bilibili
com.bilibili.app.in/tv.danmaku.bili.ui.splash.SplashActivity
https://play.google.com/store/apps/details?id=com.bilibili.app.in

- [x] Citra
org.citra.citra_emu/org.citra.citra_emu.ui.main.MainActivity
https://play.google.com/store/apps/details?id=org.citra.citra_emu

- [x] Text
com.theruralguys.stylishtext/com.theruralguys.stylishtext.activities.MainActivity
https://play.google.com/store/apps/details?id=com.theruralguys.stylishtext

- [x] Castbox
fm.castbox.audiobook.radio.podcast/fm.castbox.audio.radio.podcast.ui.main.MainActivity
https://play.google.com/store/apps/details?id=fm.castbox.audiobook.radio.podcast

- [x] Members
com.samsung.android.voc/com.samsung.android.voc.LauncherActivity
https://play.google.com/store/apps/details?id=com.samsung.android.voc

- [x] BHIM
in.org.npci.upiapp/in.org.npci.upiapp.HomeActivity
https://play.google.com/store/apps/details?id=in.org.npci.upiapp

- [x] Google Gallery Go
com.google.android.apps.photosgo/com.google.android.apps.photosgo.home.HomeActivity
https://play.google.com/store/apps/details?id=com.google.android.apps.photosgo

- [x] CameraMX
com.magix.camera_mx/com.magix.android.cameramx.main.LaunchingActivity
https://play.google.com/store/apps/details?id=com.magix.camera_mx

- [x] GoPro
com.gopro.smarty/com.gopro.smarty.activity.HomeActivity
https://play.google.com/store/apps/details?id=com.gopro.smarty

- [x] Yandex Browser
com.yandex.browser/com.yandex.browser.YandexBrowserActivity
https://play.google.com/store/apps/details?id=com.yandex.browser

- [x] Alight Motion
com.alightcreative.motion/com.alightcreative.app.motion.activities.ProjectListActivity
https://play.google.com/store/apps/details?id=com.alightcreative.motion

- [x] Digital Wellbeing
com.google.android.apps.wellbeing/com.google.android.apps.wellbeing.settings.LauncherActivity
https://play.google.com/store/apps/details?id=com.google.android.apps.wellbeing

- [x] Adblock Browser
com.hsv.freeadblockerbrowser/com.google.android.apps.chrome.Main
https://play.google.com/store/apps/details?id=com.hsv.freeadblockerbrowser

- [x] Nubank
com.nu.production/br.com.nubank.shell.screens.splash.SplashActivity
https://play.google.com/store/apps/details?id=com.nu.production

- [x] Yandex
ru.yandex.searchplugin/ru.yandex.searchplugin.MainActivity
https://play.google.com/store/apps/details?id=ru.yandex.searchplugin

- [x] Threads
com.instagram.threadsapp/com.instagram.threadsapp.main.impl.activity.MainActivity
https://play.google.com/store/apps/details?id=com.instagram.threadsapp

- [x] Poco Launcher
com.mi.android.globallauncher/com.miui.home.launcher.SplashActivity
https://play.google.com/store/apps/details?id=com.mi.android.globallauncher

- [x] Spotify Lite
com.spotify.lite/com.spotify.lite.features.launcher.LauncherActivity
https://play.google.com/store/apps/details?id=com.spotify.lite

- [ ] Mercari
com.kouzoh.mercari/com.kouzoh.mercari.activity.SplashActivity
https://play.google.com/store/apps/details?id=com.kouzoh.mercari

- [x] Canon Print
jp.co.canon.bsd.ad.pixmaprint/jp.co.canon.bsd.ad.pixmaprint.EulaActivity
https://play.google.com/store/apps/details?id=jp.co.canon.bsd.ad.pixmaprint

- [x] n7player
com.n7mobile.nplayer/com.n7mobile.nplayer.glscreen.Main
https://play.google.com/store/apps/details?id=com.n7mobile.nplayer

**Comment by leifniem** [comment]
@wokija tagging you in case you still want to help outwith icon creation, but no worries if it's bad timing :)

Everyone else reading this may of course join in too, if you feel up to the task.

I don't know if you can check the boxes in the list above, if you can please do so when working on icons, if not just announce the icons you want to work on and i will do so.

About the icons that need fixes: I think i will try to automate this as good as possible, so everyone can enjoy the fun part :)

**Comment by miszek2000** [comment]
I can't check the boxes, but for now I can work on:  Gojek, Space, Gaming, XRecorder, Careem, Stars, PPSSPP, NAVER, SmartThings. I will also do icons for apps installed on my phone.

**Comment by leifniem** [comment]
@miszek2000 Thanks, i'll tick those off then

**Comment by leifniem** [comment]
The to update is generated by the script i wrote and basically includes all package names that are already present in the appfilter.xml. So there is the possibility of them needing updates, but usually i get complaints when icons of Delta do not fit any redesigns etc.

**Comment by leifniem** [comment]
I also tend to leave all the old appfilters in so nothing breaks and older versions of apps are compatible with newer versions of Delta. Luckily that is easily manageable when having to do manual merges.

**Comment by wokija** [comment]
Okay good, I'll take a look at what need fixing first. I'll edit this comment with an updated list

**TO UPDATE**:
- [x] GitHub
Added new ComponentInfos

- [x] DuckDuckGo
Added new ComponentInfos

**Comment by leifniem** [comment]
@wokija thanks for the update thingy, much appreciated :)

I will check up on the ones you had trouble with, i know that some of those are flaws in the script i wrote to sort through the flood of mails. Also i had a Spark icon from iOS at hand, so i just added it to the update part, just forgot to push it.

**Comment by wokija** [comment]
Np, I added some more in my comment. Also, @miszek2000 completed many. Could you check them in the list please? Thanks!

I took a look at the remaining icons to create and I'm not sure I can make all of them. However I can save time to whoever work on them and add all the ComponentInfos (while leaving the drawable names for svg and png files) if it's okay.

**Comment by wokija** [comment]
If you haven't read about it, Firefox decided to remove some of their multiple apps to avoid confusion. The new Firefox Preview is gone and is merged with Firefox Nightly. So the three main apps are now Firefox, Firefox Beta and Firefox Nightly. Focus (or Klar) remains active.

I tried to edit Firefox Nightly svg file and switch the colors to Delta's but the gradients are just too messy for me to deal it. So I'm leaving this here for someone else. We could also go with a single color [like this](https://i.imgur.com/j6Pm9ZT.png) without background color, which is a slightly modified version of their "oneColor" icon. However that wouldn't match the current Delta Firefox icons.

Firefox Nightly
org.mozilla.fenix/org.mozilla.fenix.App (Already in the xml files for Firefox Preview, require an icon update)
[https://play.google.com/store/apps/details?id=org.mozilla.fenix](https://play.google.com/store/apps/details?id=org.mozilla.fenix)
Link to svg file:
[https://3u26hb1g25wn1xwo8g186fnd-wpengine.netdna-ssl.com/files/2019/10/Fx-Browser-Nightly-icon-fullColor.svg](https://3u26hb1g25wn1xwo8g186fnd-wpengine.netdna-ssl.com/files/2019/10/Fx-Browser-Nightly-icon-fullColor.svg)

**Comment by miszek2000** [comment]
> I took a look at the remaining icons to create and I'm not sure I can make all of them. However I can save time to whoever work on them and add all the ComponentInfos (while leaving the drawable names for svg and png files) if it's okay.

@wokija I think I can make the remaining to create.

**Comment by wokija** [comment]
Great! I can add the remaining ComponentInfos later today so you don't have to.

**Comment by miszek2000** [comment]
I've done all the remaining icons today. When you finish ComponentInfos, can you post the file names that you've used?

**Comment by wokija** [comment]
Done!

samsung_members
camera_mx
adblock_browser
nubank
poco_launcher

**Comment by leifniem** [comment]
@wokija @miszek2000 i made the effort of porting my sketch file to Figma as good as i could with as little effort as i thought reasonable, so if you need access i'd provide you with a link if you shoot me a mail, to improve your workflow a little if it helps.

I'll check the icons you made in the list, sorry for having so little time for Delta as of late.

**Comment by leifniem** [comment]
And again thank you both for your immense contributions :) feel free to leave the rest of the icons to me since it'll be some time before i get to bundling everything up and getting it to the play store

**Comment by KerstinMaur** [comment]
Awesome work, guys! 👍

![source](https://user-images.githubusercontent.com/32022034/87581219-dd85f200-c6d8-11ea-830d-d084fdd41cd5.gif)


By the way, can you please check the size of those icons? They seem a bit too small on my device. 🤔

- ComponentInfo{de.wetteronline.wetterapppro/de.wetteronline.wetterapp.MainActivityGoogle}

- ComponentInfo{de.hafas.android.db/de.bahn.dbtickets.ui.DBNavLauncherActivity}

- ComponentInfo{com.liveyourproject.barfinder/com.liveyourproject.barfinder.MainActivity}

- ComponentInfo{com.netflix.mediaclient/com.netflix.mediaclient.ui.launch.UIWebViewActivity}

And this is the new Huawei flashlight. Can you make it use the default Delta-themed flashligt icon please? 🔦

- ComponentInfo{com.huawei.HwMultiScreenShot/com.android.systemui.flashlight.FlashlightActivity}

Thank you so much! 🚀

**Comment by wokija** [comment]
@leifniem 
what sketch file?

@KerstinMaur 
I remember fixing Bar Finder icon, so it'll be corrected in the next app update. I'll look at the rest.

**Comment by leifniem** [comment]
@wokija a file for Sketch (the Mac app) i migrated to Figma, a web-based alternative with a nice free tier and very nice functionalities for UI design.

**Comment by wokija** [comment]
Oh, i though you used Photoshop.

**Comment by wokija** [comment]
Oh, I thought you used Illustrator

**Comment by KerstinMaur** [comment]
I might be wrong but somehow the _**DB**_ looks a bit too small, doesn't it?  🧐

![db](https://user-images.githubusercontent.com/32022034/87593621-02379500-c6ec-11ea-8d84-1f32ebae6547.jpg)

**Comment by leifniem** [comment]
@KerstinMaur 

Thats because it has a white rectangle as background and so does your drawer.

**Comment by KerstinMaur** [comment]
Yes, that's right. 
But my idea was to make the **_DB_** a bit wider so that is closer to the border.
Do you see what I mean?

![screenshot](https://user-images.githubusercontent.com/32022034/87682228-e67dce80-c77f-11ea-94ae-2e4a0227d198.jpg)

![screenshot](https://user-images.githubusercontent.com/32022034/87682676-67d56100-c780-11ea-927d-f7fa3f4bba9c.jpeg)

**Comment by wokija** [comment]
![Indeed it could be a little larger and still fit the template](https://user-images.githubusercontent.com/14982166/87698050-f2a66380-c760-11ea-820e-e26c59049498.png). I'll submit a modified version on my next commit.

**Comment by leifniem** [comment]
I'm ashamed of myself for that icon being so off-center 😂

**Comment by wokija** [comment]
Haha, no worry, it's fixed now

**Comment by KerstinMaur** [comment]
> 
> 
> Haha, no worry, it's fixed now

Thanks 😂
Can you please check Wetter Online too?

**Comment by wokija** [comment]
Wetter Online size is alright, perhaps a bit misaligned though. However, I don't have the svg file to correct it.

**Comment by Pitrr** [comment]
> I can't check the boxes, but for now I can work on:
> 
> * [x]   Gojek
> * [x]   Space
> * [x]   Gaming
> * [x]   XRecorder
> * [x]    Careem
> * [x]    Stars
> * [x]   PPSSPP
> * [x]   NAVER
> * [x]   SmartThings
> * [x]   Themes
> * [x]  Franco Kernel Manager
> * [ ]  Earth (Minecraft) - I wanted to use the Minecraft icon from Delta and change the ground color to blue, but I can't find a svg file for it.
> * [x]  Paint
> * [x]  Roblox
> * [x]  Swiggy
> * [x]  BeautyPlus
> * [x]  Prayer
> * [x]  Connect
> * [x]  Google Go
> * [x]  Phone Pe
> * [x]  Deliveroo
> * [x]  Recorder
> * [x]  PES 2020
> * [x]  Samsung USB Backup
> * [x]  Lens
> * [x]  InShot
> * [x]  Amazon Seller
> * [x]  YMusic
> * [x]  Blackboard
> * [x]  Airtel
> * [x]  Clue
> * [x]  TaoBao
> * [x]  OnePlus Notes
> * [x]  Tips
> * [x]  Pratilipi
> * [x]  Care
> 
> I will also do icons for apps installed on my phone.

Did you already finish the Google Recorder one?
It was unticked on the main todo list and I haven't noticed your comment.
:V
![image](https://user-images.githubusercontent.com/13086471/89015622-9ffba880-d317-11ea-8caa-02cf8bd20332.png)

**Comment by miszek2000** [comment]
> Did you already finish the Google Recorder one?
> It was unticked on the main todo list and I haven't noticed your comment.
> :V
Yes, I've finished it. From what I can remember it's pretty much identical to your design.

**Comment by Pitrr** [comment]
> > Did you already finish the Google Recorder one?
> > It was unticked on the main todo list and I haven't noticed your comment.
> > :V
> 
> Yes, I've finished it. From what I can remember it's pretty much identical to your design.

Fair. I'll scrap mine then

**Comment by wokija** [comment]
Since I don't know where else to put it, I'll leave this here for everyone to see. As I mentioned in a previous comment, Firefox decided to cut on apps and I figure it's a good time to update the current icons. I tried playing with gradient for the recent Firefox Nightly to keep a similar look to the original one but that wasn't looking good. So i took a flat vector file provided by Mozilla and played around to compose the current builds icons. I'd like to get some feedback because I'm not totally sure on which ones to pick. Of course they can act as Alternative icons since Firefox Stable and Beta icons are up-to-date but I still wanted to make them all to keep some sort of standard.

Tell me what you think: 
![firefox-ideas](https://user-images.githubusercontent.com/14982166/89090280-f72d6780-d36f-11ea-8c88-3e86e3001a2c.png)

**Comment by miszek2000** [comment]
> Tell me what you think:
> ![firefox-ideas](https://user-images.githubusercontent.com/14982166/89090280-f72d6780-d36f-11ea-8c88-3e86e3001a2c.png)

I like the first column the most (first column, upper row for Firefox Nightly). Fox keeps its color and white in the center brightens the whole icon. The rest of the icons are also fine alternatives. Nicely done!

**Comment by AdamGEmerson** [comment]
These new Firefox icons look clean but I really like the current Firefox icon in delta (It's one of my favorite in the set).  

I hope that the old icon will be left in as an alternative when these new ones are added.

**Comment by leifniem** [comment]
@wokija @miszek2000 Hey sorry for getting back to this only now, i sadly have my hands very full at the moment.

@AdamGEmerson I have never erased an old icon from Delta so far if i remember correctly :)

Also to everyone: @miszek2000 suggested setting up a discord channel for Delta, would y'all be up for that?

Also tagging @jamesalexatkin @Pitrr @KerstinMaur because you guys contribute quite a bunch

**Comment by Pitrr** [comment]
> @wokija @miszek2000 Hey sorry for getting back to this only now, i sadly have my hands very full at the moment.
> 
> @AdamGEmerson I have never erased an old icon from Delta so far if i remember correctly :)
> 
> Also to everyone: @miszek2000 suggested setting up a discord channel for Delta, would y'all be up for that?
> 
> Also tagging @jamesalexatkin @Pitrr @KerstinMaur because you guys contribute quite a bunch

I feel like a Telegram group would be better. They're way less restrictive because you can upload files up to 2 gigs instead of Discord's vanilla 8 MB, and you can upload images without any compression, and more. But I'm up for either one!

**Comment by jamesalexatkin** [comment]
@leifniem yeah Discord sounds like a good idea!

@AdamGEmerson I'm with you re:Firefox, the current one is really nice and one of my favs, still pastel but with more texture. Personally, I think it'd be nice to see the others done in the same style

**Comment by leifniem** [comment]
So we got Telegram vs Discord, both work in my case, the 8 MB limit should only come in as a hindrance if we share whole APKs, since the current Delta build is about 15 MB

**Comment by wokija** [comment]
@AdamGEmerson @jamesalexatkin I had no intention to overwrite @leifniem work though, It was simply an idea to make the whole Firefox icons match a bit more together for the icon pack, even as alternatives icons. To be fair, I'm running Linux at home and Inkscape makes gradients really difficult to work with. Explains why I went with a simpler icon concept 😅

Also apparently the open source project Fennec is still active. So that would be great to include it if we're updating these, gradient or not.

I agree that a Discord would be a great idea to communicate more efficiently.

**Comment by KerstinMaur** [comment]
Telegram and Discord work for me. I prefer Telegram though. 
Working with GitHub issues is fine too.

**Comment by miszek2000** [comment]
The main reason I suggested setting up a Discord server was to make it easier for us to communicate. Now I have to scroll down through a lot of comments to read the latest one (so painful on mobile).

I don't know if it's possible on Telegram, but on Discord, we can make multiple channels on the server for different topics.

I'm open to other platforms, I just have more experience with Discord.

**Comment by Pitrr** [comment]
@miszek2000 Both are pretty different. Even though it may seem like having a single group might be unorganized, I have never found it to be the case. Telegram has a way better quoting system that pretty much eliminates this issue, even on fairly big groups.

**Comment by leifniem** [comment]
@wokija @miszek2000 @jamesalexatkin @Pitrr @KerstinMaur i opened up a very basic server, i know we can improve it with a bot for pull requests and anything but for now it'll do :)

https://discord.gg/F9RFqHN

**Comment by leifniem** [comment]
I'll close this now since the next update will have a seperate checklist for the sake of readability.
